feat: rory command!!!
PrismLauncher/bot pull request #59
Opened 2022-12-23 04:59 UTC by Chew

The `/rory` command is here!

Inspired by [Chewbotcca's `/rory`](https://github.com/Chewbotcca/Discord/blob/main/src/main/java/pw/chew/chewbotcca/commands/fun/RoryCommand.java), you can type `/rory` for a random Rory, and `/rory id:x` for a specific Rory.

This handles if an error occurs, as well.

This uses the official [Rory API](https://rory.cat/purr), hosted on the official [Rory Website](https://rory.cat). Basically... Rory!!

TypeScript is still not that fun tbh

2022-12-23 08:54 UTC, ryanccn requested changes
Please format with Prettier 😭 there are four-space indentations

 Otherwise cool :>

2022-12-24 04:24 UTC, Chew commented
They did say prettier was opinionated I suppose...

2022-12-24 05:06 UTC, ryanccn commented
> They did say prettier was opinionated I suppose...

![catquake](https://cdn.discordapp.com/emojis/1039218794528247888.png?size=32&quality=lossless)

2022-12-24 05:06 UTC, ryanccn approved these changes

2022-12-24 05:06 UTC, merged